/etc/shinit_v2: line 3: sed: command not found
/etc/shinit_v2: line 8: hostname: command not found
/etc/shinit_v2: line 42: dpkg: command not found
/uge_mnt/var/spool/uge/dl-gtn01/job_scripts/7997928: line 8: bash: command not found
/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1025: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
Traceback (most recent call last):
  File "/uge_mnt/home/dinesh/SENG/Pytorch/cifar10/main_ekfac.py", line 355, in <module>
    main()
  File "/uge_mnt/home/dinesh/SENG/Pytorch/cifar10/main_ekfac.py", line 131, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/uge_mnt/home/dinesh/SENG/Pytorch/cifar10/main_ekfac.py", line 337, in main_worker
    train_loss, train_acc = train(epoch)
  File "/uge_mnt/home/dinesh/SENG/Pytorch/cifar10/main_ekfac.py", line 286, in train
    outputs = net(inputs)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/uge_mnt/home/dinesh/SENG/Pytorch/cifar10/models/vgg_ex.py", line 24, in forward
    x = self.features(x)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/uge_mnt/home/dinesh/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 719, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (512x1x1). Calculated output size: (512x0x0). Output size is too small
